INSERT INTO TRADE_STATUS(NO, NAME) VALUES (1, '판매중');
INSERT INTO TRADE_STATUS(NO, NAME) VALUES (2, '예약중');
INSERT INTO TRADE_STATUS(NO, NAME) VALUES (3, '거래완료');
INSERT INTO TRADE_STATUS(NO, NAME) VALUES (4, '삽니다');

COMMIT;